### ISSUE TITLE
Deploy to Heroku Error

### ISSUE THREAD

**Issue by Yatharth1405** [jbergant/Chatbot-for-Website-with-React#1]
I can't find a solution to this problem. Could you please help me?

2019-04-03T15:34:30.018725+00:00 app[web.1]: Auth error:Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
2019-04-03T15:34:30.022040+00:00 app[web.1]: (node:23) UnhandledPromiseRejectionWarning: Error: 14 UNAVAILABLE: Getting metadata from plugin failed with error: error:0906D06C:PEM routines:PEM_read_bio:no start line
2019-04-03T15:34:30.022042+00:00 app[web.1]: at Object.exports.createStatusError (/app/node_modules/grpc/src/common.js:91:15)
2019-04-03T15:34:30.022044+00:00 app[web.1]: at Object.onReceiveStatus (/app/node_modules/grpc/src/client_interceptors.js:1204:28)
2019-04-03T15:34:30.022045+00:00 app[web.1]: at InterceptingListener._callNext (/app/node_modules/grpc/src/client_interceptors.js:568:42)
2019-04-03T15:34:30.022046+00:00 app[web.1]: at InterceptingListener.onReceiveStatus (/app/node_modules/grpc/src/client_interceptors.js:618:8)
2019-04-03T15:34:30.022048+00:00 app[web.1]: at callback (/app/node_modules/grpc/src/client_interceptors.js:845:24)
2019-04-03T15:34:30.022138+00:00 app[web.1]: (node:23) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
2019-04-03T15:34:30.022213+00:00 app[web.1]: (node:23) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2019-04-03T15:34:59.941184+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=POST path="/api/df_text_query" host=salty-chamber-61057.herokuapp.com request_id=c6e3b41e-680d-4e7d-9607-893dacee28dc fwd="45.123.218.243" dyno=web.1 connect=1ms service=30000ms status=503 bytes=0 protocol=https
![cmd_1](https://user-images.githubusercontent.com/49262715/55531784-1c9d5900-56c9-11e9-8613-fef5a570d9cc.png)
![cmd_2](https://user-images.githubusercontent.com/49262715/55531786-1d35ef80-56c9-11e9-8774-c6dd67e37cb0.png)

**Comment by Yatharth1405** [comment]
SOLVED

For windows
JSON.parce(process.env.PRIVATE_KEY)

**Comment by SDA141832** [comment]
Hey Yatharth where do we write the code
